import { z } from "astro:content";

export const categoryType = z.enum([
  "власні огляди",
  "дружні огляди",
  "огляди від підписників",
  "пост",
]);

export const statusType = z.enum([
  "prebuild",
  "to create",
  "to enrich",
  "to publish",
  "published",
  "needs update",
  "to update",
]);

export const volumeType = z.enum([
  "2",
  "1.5",
  "1.25",
  "1",
  "0.9",
  "0.75",
  "0.553",
  "0.5",
  "0.48",
  "0.473",
  "0.45",
  "0.449",
  "0.44",
  "0.355",
  "0.33",
  "0.25",
  "0.24",
  "0.15"
]);

export const beverageType = z.enum([
  "alco",
  "cider",
  "ayran",
  "coffee",
  "energy",
  "fizzy",
  "juice",
  "kvass",
  "plant-based",
  "radler",
  "tea",
  "water",
  "other",
]);

export const containerType = z.enum(["can", "glass", "plastic", "tetrapak"]);

export const manufacturerType = z.enum([
  "волинський бровар",
  "день у день",
  "іт ізі",
  "квас бевериджиз",
  "моршинська",
  "оболонь",
  "своя лінія",
  "чернігівське",
  "яготинське",
  "bitburger graugruppe",
  "buvette",
  "carlsberg",
  "coca-cola",
  "foodcare",
  "hell",
  "kaufland dienstleistung",
  "monster beverage",
  "new products",
  "NGS beverages",
  "pepsi",
  "radeberger gruppe",
  "redbull",
  "royal swinkels",
  "royal unibrew",
  "sandora",
  "splendid drinks",
  "tairovo",
  "van pur",
  "vitmark",
]);

export const packagerType = z.enum([
  "ag",
  "amp",
  "bagpak",
  "ball",
  "canpack",
  "crown",
  "quality",
]);

export const brandType = z.enum([
  "28 black",
  "4move",
  "воля",
  "воля/кава",
  "грузинський букет",
  "ДВІЖ",
  "день у день",
  "живчик",
  "живчик/mono",
  "квас тарас",
  "львівське",
  "моршинська",
  "розумний вибір",
  "садочок",
  "своя лінія",
  "чернігівське",
  "яготинське",
  "aquarte",
  "arizona",
  "b52",
  "battery",
  "battery/juiced",
  "booster",
  "bronx",
  "bronx/zero",
  "buevette",
  "bummer",
  "burn",
  "candy can",
  "candy can/pacman",
  "candy can/toxic waste",
  "celsius",
  "cheat code",
  "cola",
  "crazy tiger",
  "crazy wolf",
  "dark dog",
  "dr pepper",
  "effect",
  "ever aid/bubble tea",
  "exstase",
  "fanta",
  "fratelli",
  "frugo",
  "garage",
  "garage/zero",
  "gardenz",
  "gosser",
  "hanf",
  "happy joe",
  "hell",
  "hell/coffee",
  "hell/plus",
  "hell/spritz",
  "hell/summer",
  "hike/vibe",
  "ice wolf",
  "jacobs",
  "jaffa",
  "johan freitag",
  "king's bridge",
  "lomza",
  "maison perrier/energize",
  "mojo",
  "moloko",
  "monster",
  "monster/juiced",
  "monster/nitro",
  "monster/racing",
  "monster/rehab",
  "monster/ultra",
  "nonstop",
  "nonstop/juice",
  "nonstop/stalker",
  "pitbull",
  "power taurine",
  "pulls",
  "redbull",
  "redbull/edition",
  "redbull/organics",
  "revo",
  "revo/energy",
  "revo/love_is",
  "revo/next",
  "rockstar",
  "sangria",
  "schofferhofer",
  "senor cartel",
  "shake",
  "shake/zero",
  "solveza",
  "toosecco",
  "vega milk",
  "x2",
  "zibert",
]);
